config/routes.rb
Jets.application.routes.draw do
  resources :users
  resources :meals do
    member do
      get "show_image"
    end
  end

  resources :materials
  root "jets/public#show"
  any "*catchall", to: "jets/public#show"
end

app/models/application_item.rb
class ApplicationItem < Dynomite::Item
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/material.rb
class Material < ApplicationRecord
  has_one :usage, dependent: :restrict_with_error
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :user
  has_many :usages
  accepts_nested_attributes_for :usages, allow_destroy: true
  mount_uploader :photo, PhotoUploader
end

app/models/usage.rb
class Usage < ApplicationRecord
  belongs_to :meal
  belongs_to :material
end

app/models/user.rb
class User < ApplicationRecord
  has_many :meals
  has_many :photos

  has_secure_password validations: true

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < Jets::Controller::Base
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
    before_action :set_material, only: %i[show edit update delete]
  
  # GET /materials
  def index
    @materials = Material.all
  end

  # GET /materials/1
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit 
  end

  # POST /materials
  def create
    @material = Material.new(material_params)
    if @material.save
      redirect_to material_path(@material)
    else
      render :new
    end
  end

  # PUT /materials/1
  def update
    @material.update(material_params)
    redirect_to material_path(@material)
  end

  # DELETE /materials/1
  def delete
    if @material.destroy
      redirect_to materials_path
    else
      @error_message = "使用中のため削除できません"
      @materials = Material.all
      render :index
    end
  end

  private

    def set_material
      @material = Material.find(params[:id])
    end

    def material_params
      params.require(:material).permit(%i[name unit price])
    end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: [:show, :edit, :update, :delete]

  # GET /meals
  def index
    @meals = Meal.all
  end

  # GET /meals/1
  def show
  end

  # GET /meals/new
  def new
    @meal = Meal.new
    @usage = @meal.usages.new
  end

  # GET /meals/1/edit
  def edit
  end

  # Meal /meals
  def create
    @meal = Meal.new(meal_params)
    if @meal.photo != nil
          @meal.photo = @meal.photo.read
    end

    if @meal.save
      redirect_to meal_path(@meal)
    else
      render :new
    end
  end

  # PUT /meals/1
  def update
    if @meal.update(meal_params)
      redirect_to meal_path(@meal)
    else
      render :edit
    end
  end

  # DELETE /meals/1
  def delete
    @meal.destroy
    redirect_to meals_path
  end

  def show_image
    image = Meal.find params[:meal_id]
    ext = 'image/jpeg'
    render plain: image.photo, layout: false, content_type: ext
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_meal
    @meal = Meal.find(params[:meal_id])
  end

  def meal_params
    params.require(:meal).permit(:title, :photo, :make, usages_attributes: %i[meal_id material_id amount])
  end
end

app/controllers/usages_controller.rb
class UsagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: %i[show edit update delete]
  
  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit 
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  # PUT /users/1
  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  # DELETE /users/1
  def delete
    @user.destroy
    redirect_to users_path
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(%i[name email password password_confirmation])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/usages_helper.rb
module UsagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>Bulma</strong> by <a href="https://jgthms.com">Jeremy Thomas</a>. The source code is licensed
      <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
      is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
    </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a href="/mypage/analytics" class="navbar-item">
        <i class="fas fa-chart-bar mr-1"></i>
        Analytics
      </a>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          <i class="fas fa-globe mr-1"></i>
          Meal
        </a>
        <div class="navbar-dropdown">
          <a href="/materials" class="navbar-item">
            Materials
          </a>
          <hr class="navbar-divider">
          <a href="/meals" class="navbar-item">
            Meals
          </a>
        </div>
      </div>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          <i class="fas fa-cog mr-1"></i>
          Setting
        </a>
        <div class="navbar-dropdown">
          <a href="/users" class="navbar-item">
            <i class="fas fa-users mr-1"></i>
            Users
          </a>
          <hr class="navbar-divider">
        </div>
      </div>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
         
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="theme-color" content="#000000">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <%= csrf_meta_tags %>
  <title>Jets App</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  <link rel="shortcut icon" href="<%= favicon_path %>">
</head>
<body>
<section class="starter">
  <%= render 'header' %>
  <div class="container my-6 pb-6">
    <div class="row">
      <div class="col-md-9 content-body">
        <% if @title %><h1><%= @title %></h1><% end %>
        <%= yield %>
      </div>
    </div>
  </div>
  <%= render 'footer' %>
</section>
</body>
</html>

app/views/materials/_form.html.erb
<%= form_with(model: [material], local: true) do |form| %>
    <% if material.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(material.errors.count, "error") %> prohibited this material from being saved:</h2>
        <ul>
          <% material.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <%= form.label :材料名 %>
    <%= form.text_field :name, required: true, class: 'input' %>

    <%= form.label :単位 %>
    <%= form.text_field :unit, required: true, class: 'input' %>

    <%= form.label :料金目安 %>
    <%= form.text_field :price, class: 'input' %>

    <div class="mt-5 pt-5">
    <%= form.submit class: 'button is-success' %>
    </div>
  <% end %>
  

app/views/materials/edit.html.erb
<div class="columns">
  <div class="column">
    <h1 class="title is-1">Editing Material</h1>
  </div>
  <div class="column has-text-right">
    <%= link_to '<i class="fas fa-chevron-left mr-1"></i> Back'.html_safe, materials_path, class: 'button mr-3' %>
    <%= link_to '<i class="fas fa-file-alt mr-1"></i> Show'.html_safe, [@material], class: 'button is-info' %>
  </div>
</div>
<%= render 'materials/form', material: @material %>

app/views/materials/index.html.erb
<div class="columns">
  <div class="column">
    <h1 class="title is-1">Materials</h1>
  </div>
  <div class="column has-text-right">
    <%= link_to '<i class="fas fa-file-medical mr-1"></i>New'.html_safe, new_material_path, class: 'button' %>
  </div>
</div>

<div class="error">
  <% if @error_message %>
    <p style="color:#f00;"><%= @error_message %></p>
  <% end %>
</div>

<% if @materials.present? %>
  <table class="table is-fullwidth">
    <thead>
      <tr>
        <th>材料名</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @materials.each do |material| %>
        <tr class="jets-element-to-delete">
          <td><%= material.name %></td>
          <td class="has-text-right">
              <%= link_to '<i class="fas fa-file-alt"></i>'.html_safe, [material] %>
              <%= link_to '<i class="fas fa-pencil-alt ml-3"></i>'.html_safe, edit_material_path(material) %>
              <%= button_to '削除', [material], method: :delete, form_class: "far fa-trash-alt" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="notification is-warning">
    Data Not Found.
  </div>
<% end %>

app/views/materials/new.html.erb
<div class="columns">
  <div class="column">
    <h1 class="title is-1">New Material</h1>
  </div>
  <div class="column has-text-right">
    <%= link_to '<i class="fas fa-chevron-left mr-1"></i> Back'.html_safe, materials_path, class: 'button mr-3' %>
  </div>
</div>

<%= render 'materials/form', material: @material %>

app/views/materials/show.html.erb
<div class="columns">
  <div class="column">
    <h1 class="title is-1">Show Material</h1>
  </div>
  <div class="column has-text-right">
    <%= link_to '<i class="fas fa-chevron-left mr-1"></i> Back'.html_safe, materials_path, class: 'button mr-3' %>
  </div>
</div>

<p>
  <strong>材料:</strong>
  <%= @material.name %>
</p>

<p>
  <strong>量:</strong>
  <%= @material.unit %>
</p>

<p>
  <strong>料金目安:</strong>
  <%= @material.price %>
</p>

<div class="mt-5 pt-5">
  <%= link_to 'Edit', edit_material_path(@material), class: 'button is-success' %>
</div>

app/views/meals/_form.html.erb
<div class="columns is-gapless">
  <div class="column">
    <%= form_with(model: [meal], local: true, class: 'mr-5') do |form| %>
      <% if meal.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

          <ul>
            <% meal.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form.label :食品目 %>
      <%= form.text_field :title, class: 'input' %>

      <%= form.label :写真 %><br>
      <%= form.file_field :photo %>
      <br>
      <br>

    <table>
      <thead>
        <tr>
          <th>材料名</th>
          <th>数量</th>
        </tr>
      </thead>
      <tbody class="bulk-registration-form">
      <% 2.times do %>
        <%= form.fields_for :usages do |usage| %>
          <tr>
            <td><%= usage.collection_select :material_id, Material.all, :id, :name, prompt: "選択してください" %></td>
            <td><%= usage.text_field :amount, class: 'input' %></td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>

      <br>
      <%= form.label :作り方 %>
      <%= form.text_area :make, class: 'textarea', rows: 20, style: 'font-size:10px' %>

      <div class="mt-5 pt-5">
        <%= form.submit class: 'button is-success' %>
      </div>
    <% end %>
  </div>
  <div class="column">
    <iframe width="100%" height="900" style="zoom:0.5;"><html></html></iframe>
  </div>
</div>

app/views/meals/edit.html.erb
<div class="columns">
  <div class="column">
    <h1 class="title is-1">Editing Meal</h1>
  </div>
  <div class="column has-text-right">
    <%= link_to '<i class="fas fa-chevron-left mr-1"></i> Back'.html_safe, meals_path, class: 'button mr-3' %>
    <%= link_to '<i class="fas fa-file-alt mr-1"></i> Show'.html_safe, [@meal], class: 'button is-info' %>
  </div>
</div>
<%= render 'meals/form', meal: @meal %>

app/views/meals/index.html.erb
<div class="columns">
  <div class="column">
    <h1 class="title is-1">Meals</h1>
  </div>
  <div class="column has-text-right">
    <%= link_to '<i class="fas fa-file-medical mr-1"></i>New'.html_safe, new_meal_path, class: 'button' %>
  </div>
</div>

<% if @meals.present? %>
  <table class="table is-fullwidth">
    <thead>
      <tr>
        <th>料理名</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @meals.each do |meal| %>
        <tr class="jets-element-to-delete">
          <td><%= meal.title %></td>
          <td class="has-text-right">
            <%= link_to '<i class="fas fa-file-alt"></i>'.html_safe, [meal] %>
            <%= link_to '<i class="fas fa-pencil-alt ml-3"></i>'.html_safe, edit_meal_path(meal) %>
            <%= button_to '削除', [meal], method: :delete, form_class: "far fa-trash-alt" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="notification is-warning">
    Data Not Found.
  </div>
<% end %>

app/views/meals/new.html.erb
<div class="columns">
  <div class="column">
    <h1 class="title is-1">New Meal</h1>
  </div>
  <div class="column has-text-right">
    <%= link_to '<i class="fas fa-chevron-left mr-1"></i> Back'.html_safe, meals_path, class: 'button mr-3' %>
  </div>
</div>

<%= render 'meals/form', meal: @meal %>

app/views/meals/show.html.erb
<div class="columns">
  <div class="column">
    <h1 class="title is-1">Show Meal</h1>
  </div>
  <div class="column has-text-right">
    <%= link_to '<i class="fas fa-chevron-left mr-1"></i> Back'.html_safe, meals_path, class: 'button mr-3' %>
  </div>
</div>

<p>
  <strong>写真</strong><br>
  <br>
  <%= image_tag show_image_meal_path(@meal) %>
</p>
<br>
<p>
  <strong>食品名</strong><br>
  <%= @meal.title %>
</p>
<br>

<table>
  <tr>
    <th>材料名</th>
    <th>使用量(g)</th>
    <th>材料費</th>
  </tr>
  <% @meal.usages.each do |usage| %>
    <% p @meal.usages %>
    <% p usage %>
  <tr>
    <td><%= usage.material.name %></td>
    <td><%= usage.amount %></td>
    <td><%= usage.material.price.to_i / usage.material.unit.to_i * usage.amount.to_i %>円</td>
  </tr>
  <% end %>
</table>
<br>
<p>
  <strong>作り方</strong><br>
  <%=safe_join(@meal.make.split("\n"),tag(:br))%>
</p>

<div class="mt-5 pt-5">
  <%= link_to 'Edit', edit_meal_path(@meal), class: 'button is-success' %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: [user], local: true) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
          <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <%= form.label :name %>
    <%= form.text_field :name, required: true, class: 'input' %>

    <%= form.label :email %>
    <%= form.text_field :email, required: true, class: 'input' %>

    <%= form.label :新pass %>
    <%= form.password_field :password, class: 'input' %>

    <%= form.label :確認pass %>
    <%= form.password_field :password_confirmation, class: 'input', placeholder: "パスワードを再入力" %>

    <div class="mt-5 pt-5">
    <%= form.submit class: 'button is-success' %>
    </div>
  <% end %>
  

app/views/users/edit.html.erb
<div class="columns">
  <div class="column">
    <h1 class="title is-1">Editing User</h1>
  </div>
  <div class="column has-text-right">
    <%= link_to '<i class="fas fa-chevron-left mr-1"></i> Back'.html_safe, users_path, class: 'button mr-3' %>
    <%= link_to '<i class="fas fa-file-alt mr-1"></i> Show'.html_safe, [@user], class: 'button is-info' %>
  </div>
</div>
<%= render 'users/form', user: @user %>

app/views/users/index.html.erb
<div class="columns">
  <div class="column">
    <h1 class="title is-1">Users</h1>
  </div>
  <div class="column has-text-right">
    <%= link_to '<i class="fas fa-file-medical mr-1"></i>New'.html_safe, new_user_path, class: 'button' %>
  </div>
</div>

<% if @users.present? %>
  <table class="table is-fullwidth">
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr class="jets-element-to-delete">
          <td><%= user.name %></td>
          <td class="has-text-right">
            
              <%= link_to '<i class="fas fa-file-alt"></i>'.html_safe, [user] %>
              <%= link_to '<i class="fas fa-pencil-alt ml-3"></i>'.html_safe, edit_user_path(user) %>
              <%= button_to '削除', [user], method: :delete, form_class: "far fa-trash-alt" %>     
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="notification is-warning">
    Data Not Found.
  </div>
<% end %>

app/views/users/new.html.erb
<div class="columns">
  <div class="column">
    <h1 class="title is-1">New User</h1>
  </div>
  <div class="column has-text-right">
    <%= link_to '<i class="fas fa-chevron-left mr-1"></i> Back'.html_safe, users_path, class: 'button mr-3' %>
  </div>
</div>

<%= render 'users/form', user: @user %>

app/views/users/show.html.erb
<div class="columns">
  <div class="column">
    <h1 class="title is-1">Show User</h1>
  </div>
  <div class="column has-text-right">
    <%= link_to '<i class="fas fa-chevron-left mr-1"></i> Back'.html_safe, users_path, class: 'button mr-3' %>
  </div>
</div>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<div class="mt-5 pt-5">
  <%= link_to 'Edit', edit_user_path(@user), class: 'button is-success' %>
</div>